-- CREATE TABLE practical2.customer
-- (
-- 	cid		varchar(3),
--     name 	char(10)
-- );

-- 
-- insert into practical2.customer
-- values('C01','Riya');
-- 
-- insert into practical2.customer
-- values('C02','Jiya');
-- 
-- insert into practical2.customer
-- values('C03','Diya');
-- 
-- insert into practical2.customer
-- values('C04','Taral');
-- 
-- insert into practical2.customer
-- values('C05','Saral');
-- 
-- truncate practical2.customer;


-- CREATE TABLE practical2.employee2
-- (
-- 	eid			varchar(3),
--     name 		char(10),
--     mngr_ig		varchar(3)
-- );

-- 
-- insert into practical2.employee2
-- values('E01','Palak','E02');
-- 
-- insert into practical2.employee2
-- values('E02','Zalak','');
-- 
-- insert into practical2.employee2
-- values('E03','Falak','E02');
-- 
-- insert into practical2.employee2
-- values('E04','Taral','E02');
-- 
-- insert into practical2.employee2
-- values('E05','Saral','E02');